apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-np
  namespace: tarefa8
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30800
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-clusterip
  namespace: tarefa8
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
