apiVersion: v1
kind: Service
metadata:
  name: registry-svc
  namespace: registry 
spec:
  selector:
    app: registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
  type: NodePort
