kind: Service
apiVersion: v1
metadata:
  name: trouble-svc
spec:
  type: NodePort
  selector: 
    app.kubernetes.io/name: TroubleShooting
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
